server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-consumer
    api-b:
      path: /api-b/**
      serviceId: feign-consumer